# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0740658c2a3bccf13c8500881144047b7c66ea52b7e80b706d514b2953cc118e1274fc55acc6e13c14091ea6fbe8f2413fd1b7573a002e32134fd93f1d647e7e

test:
  secret_key_base: e25cd204d2420296d23d6b397b542cd750066d846c3e3d526f2af020d61890dbd482292915c62a29afac404d84c7ebde12079cdcc9960826bfc0e082099f9f4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
